# Generated by Django 4.1.2 on 2022-11-30 14:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.SlugField(blank=True, max_length=20, null=True)),
                ('tag2', models.SlugField(blank=True, max_length=20, null=True)),
                ('tag3', models.SlugField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('unique_identity', models.UUIDField(default=uuid.UUID('46bc68ee-38b4-494e-a497-8c250cb58285'), primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
