# Generated by Django 4.1.2 on 2022-11-30 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='unique_identity',
            field=models.UUIDField(default=uuid.UUID('8f3c7f6d-000c-4162-ae15-d0dae49a6df2'), primary_key=True, serialize=False),
        ),
    ]
