# Generated by Django 4.1.2 on 2022-11-30 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_note_unique_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='unique_identity',
            field=models.UUIDField(default=uuid.UUID('423d02d1-a845-453d-95fb-0de40b7533c5'), primary_key=True, serialize=False),
        ),
    ]
